version: '3'
services:
  golang:
    build:
      context: .
      args:
        USER: $USER
        UID: $UID
    image: golang-app
    volumes:
      - ./go:/go
    command: sh ./start.sh
    env_file:
      - .env
    container_name: golang-app
